const INVALID_DATA = 400;
const INVALID_ENDPOINT = 404;
const UNAUTHORIZED = 401;
const SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;
const FORBIDDEN_ERROR = 403;

module.exports = {
  INVALID_DATA,
  INVALID_ENDPOINT,
  SERVER_ERROR,
  UNAUTHORIZED,
  CONFLICT_ERROR,
  FORBIDDEN_ERROR,
};
